# Generated by Django 6.0.4 on 2026-04-25 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rareza', models.CharField(choices=[('COMUN', 'Común'), ('RARA', 'Rara'), ('EPICA', 'Épica'), ('MITICA', 'Mítica'), ('LEGENDARIA', 'Legendaria')], default='COMUN', max_length=20)),
                ('tipo', models.CharField(choices=[('PERSONAJE', 'Personaje'), ('OBJETO', 'Objeto (Equipo)'), ('ENTORNO', 'Entorno'), ('CONSUMIBLE', 'Consumible')], default='PERSONAJE', max_length=20)),
                ('categoria', models.CharField(help_text='Ej: Ficción, Real, Mito', max_length=50)),
                ('hp', models.IntegerField(default=0, help_text='Vida de la carta')),
                ('atk', models.IntegerField(default=0, help_text='Ataque de la carta')),
                ('costo_invocacion', models.IntegerField(default=1, help_text='Energía necesaria en mesa')),
                ('costo_accion', models.IntegerField(default=1, help_text='Energía que gasta al atacar')),
                ('descripcion_efecto', models.TextField(blank=True, null=True)),
                ('costo_uso', models.IntegerField(default=1, help_text='Energía para activar soporte')),
                ('imagen_url', models.URLField(help_text='URL del arte del personaje', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id_game', models.CharField(max_length=20, unique=True)),
                ('monedas', models.IntegerField(default=500)),
                ('diamantes', models.IntegerField(default=10)),
                ('nivel', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mazo', models.CharField(default='Mi Mazo Principal', max_length=50)),
                ('cartas', models.ManyToManyField(help_text='Selecciona las cartas para este mazo', to='game.carta')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.carta')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_cartas', to='game.perfil')),
            ],
        ),
    ]
