# Generated by Django 6.0.4 on 2026-05-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagen_url',
            field=models.CharField(help_text='Ruta: /cartas/nombre.png', max_length=500),
        ),
    ]
