# Generated by Django 6.0.4 on 2026-05-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_carta_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='monedas',
            new_name='creditos',
        ),
    ]
