# Generated by Django 6.0.4 on 2026-05-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_monedas_perfil_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen_banner', models.CharField(help_text='Ruta o URL del banner para el Home', max_length=500)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Para ocultar colecciones en desarrollo')),
            ],
            options={
                'verbose_name_plural': 'Colecciones',
            },
        ),
        migrations.AddField(
            model_name='carta',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='game.coleccion'),
        ),
    ]
